version: 1.2
workflows:
- name: ONT10x
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/ONT10x.wdl
- name: ONTWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/VariantCalling/ONTWholeGenome.wdl
- name: ONTFlowcell
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Preprocessing/ONTFlowcell.wdl
- name: PBFlowcell
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Alignment/PBFlowcell.wdl
- name: PBCCS
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCCS.wdl
- name: PBCCS10x
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCCS10x.wdl
- name: PBCCSDemultiplex
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCCSDemultiplex.wdl
- name: PBCCSDemultiplexWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCCSDemultiplexWholeGenome.wdl
- name: PBCCSIsoSeq
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Utility/PBCCSIsoSeq.wdl
- name: PBCCSWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/VariantCalling/PBCCSWholeGenome.wdl
- name: PBCLRDemultiplexWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCLRDemultiplexWholeGenome.wdl
- name: PBCLRWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/VariantCalling/PBCLRWholeGenome.wdl
- name: LRCNVs
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/VariantCalling/LRCNVs.wdl
- name: ONTBasecall
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Preprocessing/ONTBasecall.wdl
- name: ONTAssembleWithCanu
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Assembly/ONTAssembleWithCanu.wdl
- name: ONTAssembleWithFlye
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Assembly/ONTAssembleWithFlye.wdl
- name: VerifyFingerprint
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/VerifyFingerprint.wdl
- name: DownloadFromHudsonAlpha
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/DownloadFromHudsonAlpha.wdl
- name: PBAssembleWithHifiasm
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/PBAssembleWithHifiasm.wdl
- name: ONTMethylation
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Epigenomics/ONTMethylation.wdl
- name: ONTPfHrp2Hrp3Status
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/MultiAnalysis/ONTPfHrp2Hrp3Status.wdl
- name: ONTPfTypeDrugResistanceMarkers
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/MultiAnalysis/ONTPfTypeDrugResistanceMarkers.wdl
- name: PBMASIsoSeqQuantify
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Utility/PBMASIsoSeqQuantify.wdl
- name: PBMASIsoSeqDemultiplex
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Utility/PBMASIsoSeqDemultiplex.wdl
- name: LRJointCallGVCFs
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/VariantCalling/LRJointCallGVCFs.wdl
- name: ConvertToHailMT
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/ConvertToHailMT.wdl
- name: LRConvertBCF
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/LRConvertBCF.wdl
- name: DownloadFromSRA
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/DownloadFromSRA.wdl
- name: DownloadFromWeb
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/DownloadFromWeb.wdl
- name: ONTProcessBasecall
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Preprocessing/ONTProcessBasecall.wdl
- name: ONTFlowcellFromMultipleBasecalls
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Preprocessing/ONTFlowcellFromMultipleBasecalls.wdl
  primaryDescriptorPath: /wdl/LRConvertBCF.wdl
- name: IllumAssembleWithFusilli
  subclass: wdl
  primaryDescriptorPath: /wdl/IllumAssembleWithFusilli.wdl
  testParameterFiles:
- name: IllumAssembleWithFusilliContinue
  subclass: wdl
  primaryDescriptorPath: /wdl/IllumAssembleWithFusilliContinue.wdl
  testParameterFiles:
- name: IllumAssembleWithMcCortex
  subclass: wdl
  primaryDescriptorPath: /wdl/IllumAssembleWithMcCortex.wdl
  testParameterFiles:
- name: IllumAssembleWithSPAdes
  subclass: wdl
  primaryDescriptorPath: /wdl/IllumAssembleWithSPAdes.wdl
  testParameterFiles:
- name: IllumPlasmidSPAdes
  subclass: wdl
  primaryDescriptorPath: /wdl/IllumPlasmidSPAdes.wdl
  testParameterFiles:
- name: IllumTrimReads
  subclass: wdl
  primaryDescriptorPath: /wdl/IllumTrimReads.wdl
  testParameterFiles:
- name: IllumErrorCorrectBayesHammer
  subclass: wdl
  primaryDescriptorPath: /wdl/IllumErrorCorrectBayesHammer.wdl
  testParameterFiles:
- name: QuastEval
  subclass: wdl
  primaryDescriptorPath: /wdl/QuastEval.wdl
  testParameterFiles:
- name: UpdatePlasmidDB
  subclass: wdl
  primaryDescriptorPath: /wdl/UpdatePlasmidDB.wdl
  testParameterFiles:
- name: BaktaDownloadDB
  subclass: wdl
  primaryDescriptorPath: /wdl/BaktaDownloadDB.wdl
  testParameterFiles:
- name: BaktaAnnotateSingle
  subclass: wdl
  primaryDescriptorPath: /wdl/BaktaAnnotateSingle.wdl
  testParameterFiles:
- name: BaktaAnnotateBatch
  subclass: wdl
  primaryDescriptorPath: /wdl/BaktaAnnotateBatch.wdl
  testParameterFiles:
- name: RunPanaroo
  subclass: wdl
  primaryDescriptorPath: /wdl/RunPanaroo.wdl
  testParameterFiles:
